// Generated Vulkan Application
// This file is auto-generated by Vulkan Editor

#include "vulkan_renderer.h"

int main(int argc, char* argv[]) {
    VulkanRenderer renderer;

    try {
        renderer.init();
        renderer.run();
        renderer.cleanupRenderer();
    } catch (const std::exception& e) {
        std::cerr << "Error: " << e.what() << std::endl;
        return EXIT_FAILURE;
    }

    return EXIT_SUCCESS;
}
